### ISSUE TITLE
存在しない日記へのリファラ付きアクセスでエラーが起きる

### ISSUE THREAD

**Issue by hsbt** [tdiary/tdiary-core#389]
tDiay-4.0.2とruby-1.9.3で過去に書いた日記を削除したあと、Google検索からアクセスすると、以下のエラーが出る

```
TDiary::TDiaryError

bad date

/usr/share/nginx/www/diary/tdiary/view.rb:266:in `rescue in initialize'
/usr/share/nginx/www/diary/tdiary/view.rb:253:in `initialize'
(plugin/00default.rb):244:in `new'
(plugin/00default.rb):244:in `block in calc_links'
(plugin/00default.rb):239:in `each'
(plugin/00default.rb):239:in `calc_links'
(plugin/00default.rb):205:in `block (2 levels) in load_plugin'
/usr/share/nginx/www/diary/tdiary/plugin.rb:111:in `call'
/usr/share/nginx/www/diary/tdiary/plugin.rb:111:in `block in header_proc'
/usr/share/nginx/www/diary/tdiary/plugin.rb:110:in `each'
/usr/share/nginx/www/diary/tdiary/plugin.rb:110:in `header_proc'
(TDiary::Plugin#eval_src):5:in `block in eval_src'
/usr/share/nginx/www/diary/tdiary/plugin.rb:99:in `eval'
/usr/share/nginx/www/diary/tdiary/plugin.rb:99:in `block in eval_src'
/usr/share/nginx/www/diary/tdiary/core_ext.rb:112:in `block in safe'
/usr/share/nginx/www/diary/tdiary/core_ext.rb:106:in `call'
/usr/share/nginx/www/diary/tdiary/core_ext.rb:106:in `safe'
/usr/share/nginx/www/diary/tdiary/plugin.rb:98:in `eval_src'
/usr/share/nginx/www/diary/tdiary/base.rb:66:in `do_eval_rhtml'
/usr/share/nginx/www/diary/tdiary/base.rb:30:in `eval_rhtml'
/usr/share/nginx/www/diary/tdiary/view.rb:140:in `eval_rhtml'
/usr/share/nginx/www/diary/tdiary/dispatcher/index_main.rb:43:in `run'
/usr/share/nginx/www/diary/tdiary/dispatcher/index_main.rb:6:in `run'
/usr/share/nginx/www/diary/tdiary/dispatcher.rb:26:in `dispatch_cgi'
/usr/share/nginx/www/diary/index.rb:32:in `<top (required)>'
/usr/share/nginx/www/diary/index.fcgi:31:in `load'
/usr/share/nginx/www/diary/index.fcgi:31:in `block (2 levels) in <main>'
/usr/share/nginx/www/diary/index.fcgi:30:in `chdir'
/usr/share/nginx/www/diary/index.fcgi:30:in `block in <main>'
/usr/share/nginx/www/diary/misc/lib/fcgi_patch.rb:74:in `block in each_cgi'
/usr/share/nginx/www/diary/misc/lib/fcgi_patch.rb:71:in `each'
/usr/share/nginx/www/diary/misc/lib/fcgi_patch.rb:71:in `each_cgi'
/usr/share/nginx/www/diary/index.fcgi:22:in `<main>'
```

**Comment by tdtds** [comment]
自分の日記で再現したので直しました db007eb909cbdca4b71eee5ddf3ca7e27048f88b
