### ISSUE TITLE
Twitter認証がうまく動かない

### ISSUE THREAD

**Issue by tdtds** [tdiary/tdiary-core#479]
自分で追いかけてみますが、OAuthには明るくないので識者のヒントがあればいただきたく。

Gemfile.localをこんな感じにしてbundle install (tdiary-contribやtdiary-io-mongodbの影響を想定して外してみても、rubyを2.1.5に変えても結果は同じ):

```ruby
ruby '2.2.0'
gem 'tdiary-io-mongodb'
gem 'tdiary-contrib'
gem 'thin'
gem 'omniauth'
gem 'omniauth-twitter'
```

config.ruはドキュメントの通りに設定:

```ruby
$:.unshift( File.join(File::dirname( __FILE__ ), 'lib' ).untaint )
require 'tdiary/application'

use ::Rack::Reloader unless ENV['RACK_ENV'] == 'production'
base_dir = '/'
require 'tdiary/application/extensions/omniauth'
run TDiary::Application.new( base_dir )
```

環境変数は以下:

```shell
TWITTER_KEY=(略)
TWITTER_SECRET=(略)
TWITTER_NAME=tdtds
```

thinを-V付きで起動:

```shell
bundle exec thin start -p 9393 -a 0.0.0.0 -V
```

で、/update.rb にアクセスすると/auth/twitterにリダイレクトされてから以下のエラーになります(Twitterには飛ばない):

```
GET /update.rb HTTP/1.1
Host: localhost
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
Referer: http://localhost/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: ja,en-US;q=0.8,en;q=0.6
Cookie: rack.session=0caef1f98b25cce82bb8d8d26433f152344a873961949da8d810655ff18b38a4


HTTP/1.1 302 Moved Temporarily
Content-Type: text/plain
Location: /auth/twitter
Set-Cookie: rack.session=d3c07dae015447fe311d48cab57e4fca8e248e389798f7fe4f1e161574bcc277; path=/; expires=Tue, 10 Feb 2015 13:18:17 -0000; HttpOnly
Connection: close
Server: thin


GET /auth/twitter HTTP/1.1
Host: localhost
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
User-Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36
Referer: http://localhost/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: ja,en-US;q=0.8,en;q=0.6
Cookie: rack.session=d3c07dae015447fe311d48cab57e4fca8e248e389798f7fe4f1e161574bcc277


I, [2015-01-11T22:18:17.960847 #28954]  INFO -- omniauth: (twitter) Request phase initiated.
HTTP/1.1 500 Internal Server Error
Content-Type: text/plain
Connection: close
Server: thin


OAuth::Unauthorized: 401 Authorization Required

/home/sho/src/tdiarynet/vendor/bundle/gems/oauth-0.4.7/lib/oauth/consumer.rb:216:in `token_request'
/home/sho/src/tdiarynet/vendor/bundle/gems/oauth-0.4.7/lib/oauth/consumer.rb:136:in `get_request_token'
/home/sho/src/tdiarynet/vendor/bundle/gems/omniauth-oauth-1.0.1/lib/omniauth/strategies/oauth.rb:29:in `request_phase'
/home/sho/src/tdiarynet/vendor/bundle/gems/omniauth-twitter-1.1.0/lib/omniauth/strategies/twitter.rb:60:in `request_phase'
/home/sho/src/tdiarynet/vendor/bundle/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:215:in `request_call'
/home/sho/src/tdiarynet/vendor/bundle/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:183:in `call!'
/home/sho/src/tdiarynet/vendor/bundle/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
/home/sho/src/tdiarynet/vendor/bundle/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call'
/home/sho/src/tdiarynet/vendor/bundle/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:225:in `context'
/home/sho/src/tdiarynet/vendor/bundle/gems/rack-1.6.0/lib/rack/session/abstract/id.rb:220:in `call'
/home/sho/src/tdiarynet/vendor/bundle/gems/rack-1.6.0/lib/rack/urlmap.rb:66:in `block in call'
/home/sho/src/tdiarynet/vendor/bundle/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `each'
/home/sho/src/tdiarynet/vendor/bundle/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `call'
/home/sho/src/tdiarynet/lib/tdiary/application.rb:42:in `call'
/home/sho/src/tdiarynet/vendor/bundle/gems/rack-1.6.0/lib/rack/reloader.rb:44:in `call'
/home/sho/src/tdiarynet/vendor/bundle/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
/home/sho/src/tdiarynet/vendor/bundle/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
/home/sho/src/tdiarynet/vendor/bundle/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
/home/sho/src/tdiarynet/vendor/bundle/gems/thin-1.6.3/lib/thin/connection.rb:53:in `process'
/home/sho/src/tdiarynet/vendor/bundle/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'
/home/sho/src/tdiarynet/vendor/bundle/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run_machine'
/home/sho/src/tdiarynet/vendor/bundle/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run'
/home/sho/src/tdiarynet/vendor/bundle/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
/home/sho/src/tdiarynet/vendor/bundle/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
/home/sho/src/tdiarynet/vendor/bundle/gems/thin-1.6.3/lib/thin/controllers/controller.rb:87:in `start'
/home/sho/src/tdiarynet/vendor/bundle/gems/thin-1.6.3/lib/thin/runner.rb:200:in `run_command'
/home/sho/src/tdiarynet/vendor/bundle/gems/thin-1.6.3/lib/thin/runner.rb:156:in `run!'
/home/sho/src/tdiarynet/vendor/bundle/gems/thin-1.6.3/bin/thin:6:in `<top (required)>'
/home/sho/src/tdiarynet/vendor/bundle/bin/thin:23:in `load'
/home/sho/src/tdiarynet/vendor/bundle/bin/thin:23:in `<main>'
```

**Comment by smallstyle** [comment]
Twitter側のApplication Managementで，Callback URLは指定されてますか？
指定されていない場合にエラーが再現されます．

Callback URLに例えば，http://127.0.0.1/auth/twitter/callback を指定してはどうでしょうか？

**Comment by machu** [comment]
Callback URLが空の場合に同じエラーが再現しました。空の場合はTwitter側がデスクトップアプリだと認識してしまうようですね。

[How to fix OAuth::Unauthorized error for Twitter provider? ](https://github.com/intridea/omniauth/wiki/FAQ#how-to-fix-oauthunauthorized-error-for-twitter-provider)

> Also, you may need to set the Callback URL in Twitter settings. Example configuration for development environment can look like:
> `http://127.0.0.1:3000/auth/twitter/callback`

[gem 'omniauth-twitter'で認証しようとしてOAuth::Unauthorized 401 Unauthorizedなんてエラーがでたら](http://qiita.com/hirokishirai/items/5a43977a38ecd922bfb9)

> https://dev.twitter.com/apps でアプリケーションを登録する際に、Callback URLが入力必須項目でないからといって空っぽにしているとWebアプリケーションでは無くデスクトップアプリケーションとして認識しているため、Webアプリケーション上で動作しません。
> Callback URLはダミーURLで良いのでとりあえずなにかのURLを入力しておけば良いです。必要になったときに正しいURLに変更すれば良いです。

ちなみに、設定画面で指定したCallback URLは実際には使われません。Callback URLはOmniAuthが認証開始時 (request token取得時) に生成してtwitterに渡しています。ですので、ダミーURLでも動作します。

Twitter APIのcallback URLの説明には、以下のように書いてあります。ちょっと分かりにくい説明ですが、Webアプリの場合はCallback URLのフィールドの設定が必要なのですね。

> Where should we return after successfully authenticating? OAuth 1.0a applications should explicitly specify their oauth_callback URL on the request token step, regardless of the value given here. To restrict your application from using callbacks, leave this field blank.

tDiaryのドキュメントも更新します。

**Comment by tdtds** [comment]
ありゃりゃ、あそこはオプショナルだと思い込んでいました。どうもありがとう、あとで確認してから閉じます。
