### ISSUE TITLE
recent_rssプラグインを有効にするとSecurityError

### ISSUE THREAD

**Issue by machu** [tdiary/tdiary-core#481]
recent_rssプラグインを有効にし、フッターに指定する。

`<%=recent_rss 'http://www.machu.jp/diary/index.rdf' %>`

すると、SecurityErrorが発生する。ruby1.9.3, ruby2.0.0-p247, ruby2.1.5で確認。

```
SecurityError
Insecure operation - require
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rexml/source.rb:17:in `require'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rexml/source.rb:17:in `create_from'
```

該当箇所のソースは以下。`require 'stringio'`に失敗している。

```ruby
    def SourceFactory::create_from(arg)
      if arg.respond_to? :read and
          arg.respond_to? :readline and
          arg.respond_to? :nil? and
          arg.respond_to? :eof?
        IOSource.new(arg)
      elsif arg.respond_to? :to_str
        require 'stringio'
        IOSource.new(StringIO.new(arg))
```

 * cacheディレクトリにrecent_rssのキャッシュが残っている場合は、正常に動作する。
 * #452 との関連は不明。

スタックトレースは以下。

```
SecurityError
Insecure operation - require
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rexml/source.rb:17:in `require'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rexml/source.rb:17:in `create_from'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rexml/parsers/baseparser.rb:128:in `stream='
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rexml/parsers/baseparser.rb:117:in `initialize'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rexml/parsers/streamparser.rb:8:in `new'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rexml/parsers/streamparser.rb:8:in `initialize'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rexml/document.rb:241:in `new'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rexml/document.rb:241:in `parse_stream'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rss/rexmlparser.rb:17:in `_parse'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rss/parser.rb:164:in `parse'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rss/parser.rb:79:in `parse'
(plugin/recent_rss.rb):108:in `recent_rss_cache_rss'
(plugin/recent_rss.rb):38:in `recent_rss'
(TDiary::Plugin#eval_src):111:in `block in eval_src'
/Users/machu/work/tdiary/tdiary-core/lib/tdiary/plugin.rb:107:in `eval'
/Users/machu/work/tdiary/tdiary-core/lib/tdiary/plugin.rb:107:in `block in eval_src'
/Users/machu/work/tdiary/tdiary-core/lib/tdiary/core_ext.rb:121:in `block in safe'
/Users/machu/work/tdiary/tdiary-core/lib/tdiary/core_ext.rb:123:in `call'
/Users/machu/work/tdiary/tdiary-core/lib/tdiary/core_ext.rb:123:in `safe'
/Users/machu/work/tdiary/tdiary-core/lib/tdiary/plugin.rb:106:in `eval_src'
/Users/machu/work/tdiary/tdiary-core/lib/tdiary/base.rb:66:in `do_eval_rhtml'
/Users/machu/work/tdiary/tdiary-core/lib/tdiary/base.rb:30:in `eval_rhtml'
/Users/machu/work/tdiary/tdiary-core/lib/tdiary/dispatcher/index_main.rb:43:in `run'
/Users/machu/work/tdiary/tdiary-core/lib/tdiary/dispatcher/index_main.rb:6:in `run'
/Users/machu/work/tdiary/tdiary-core/lib/tdiary/dispatcher.rb:26:in `dispatch_cgi'
/Users/machu/work/tdiary/tdiary-core/lib/tdiary/dispatcher.rb:21:in `call'
/Users/machu/work/tdiary/tdiary-core/lib/tdiary/rack/valid_request_path.rb:17:in `block in call'
/Users/machu/work/tdiary/tdiary-core/lib/tdiary/rack/valid_request_path.rb:16:in `each'
/Users/machu/work/tdiary/tdiary-core/lib/tdiary/rack/valid_request_path.rb:16:in `call'
/Users/machu/work/tdiary/tdiary-core/lib/tdiary/rack/static.rb:15:in `call'
/Users/machu/work/tdiary/tdiary-core/lib/tdiary/rack/html_anchor.rb:20:in `call'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/urlmap.rb:66:in `block in call'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `each'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `call'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/urlmap.rb:66:in `block in call'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `each'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/urlmap.rb:50:in `call'
/Users/machu/work/tdiary/tdiary-core/lib/tdiary/application.rb:43:in `call'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/reloader.rb:44:in `call'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/tempfile_reaper.rb:15:in `call'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/lint.rb:49:in `_call'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/lint.rb:37:in `call'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/showexceptions.rb:24:in `call'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/commonlogger.rb:33:in `call'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/chunked.rb:54:in `call'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/content_length.rb:15:in `call'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rack-1.6.0/lib/rack/handler/webrick.rb:89:in `service'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
/Users/machu/.rbenv/versions/2.1.5/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by tamoot** [comment]
#358 のスタックトレースと同じ個所ですね。。

**Comment by tdtds** [comment]
これはいいヒントだ。$LOAD_PATHに含まれてるcontribのライブラリパスがtaintedになってる。つまりGemfile.localで指定したgemのパスがuntaintされてないってことかな?

**Comment by tdtds** [comment]
#358 と同じワークアラウンドで動くようになった。さて、どうしようかな……

**Comment by tdtds** [comment]
とりあえず$LOAD_PATHをuntaintしましたが、想定外のパスを挿入された場合にセキュアではないので、Gemfile.localに限定した場合のよりよい解決策は募集します。まぁ、ここで$LOAD_PATHに何かつっこまれるときはどうしようもないはずですが。

いったんクローズします。
