### ISSUE TITLE
Webサーバをunicornにするとrecent_rssでSecurityError

### ISSUE THREAD

**Issue by tdtds** [tdiary/tdiary-core#483]
#481 とまったく同じ現象ですが、$LOAD_PATHをすべてuntaintにしているにもかかわらずエラーになるので、別issueにしておきます。なお #481 はWebサーバをthinにして試して問題がないことを確認しました。

サーバを変えるだけで何が違ってくるというのだ……

**Comment by tdtds** [comment]
puma でも同様のエラーになります。

**Comment by tamoot** [comment]
Gemfile.localとGemfileに書く、の違いがあったりして・・・

**Comment by tdtds** [comment]
いや、thin、puma、unicorn、いずれもGemfile.localに書いてますが、recent_rssが動くのはthinだけなんすよ……

**Comment by tamoot** [comment]
参考までに、root以外のユーザでrbenvを利用したruby2.2.0の環境にて、irbでも以下となりました。

```
rbenv versions
  2.1.0
  2.1.5
* 2.2.0 (set by /home/tamoot/.rbenv/version)

```

```Ruby
irb(main):002:0> $SAFE=1
=> 1

irb(main):002:0> require 'stringio'
SecurityError: Insecure operation - gem_original_require
        from /home/tamoot/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /home/tamoot/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from (irb):2
        from /home/tamoot/.rbenv/versions/2.2.0/bin/irb:11:in `<main>'
```

**Comment by tdtds** [comment]
なんと。でもruby直だと大丈夫ですね:

```ruby
% ruby -e 'puts RUBY_VERSION; $SAFE=1; require "stringio"'
2.2.0
```

そもそもirbの中はいろいろ複雑な状態になっているので、この手の再現環境としては不適切な気がします($SAFEを変化させることが考慮されてないし)。が、同じことがunicornやpumaの中でも起きている可能性は高いですね。

**Comment by tamoot** [comment]
rbenv経由ruby直で以下のようになっています。(user:root, ruby:2.1.5)

```
ruby -e 'puts RUBY_VERSION;$SAFE=1;require "stringio"'
2.1.5
/root/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': Insecure operation - gem_original_require (SecurityError)
        from /root/.rbenv/versions/2.1.5/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
```

rbenvでないruby2.1.5環境(ruby-buildだけを使ってbuild)だと起きないです。ううむ。。。

```
git clone https://github.com/sstephenson/ruby-build.git
ruby-build/bin/ruby-build 2.1.5 /opt/tmp_ruby
cd /opt/tmp_ruby/bin
./ruby -e 'puts RUBY_VERSION;$SAFE=1;require "stringio"'
2.1.5
```

**Comment by machu** [comment]
私の環境だとrbenvでも再現しません。環境依存ですかねぇ。

```
$ ruby -e 'puts RUBY_VERSION;$SAFE=1;require "stringio"'
2.1.5
$ rbenv local 2.2.0
$ ruby -e 'puts RUBY_VERSION;$SAFE=1;require "stringio"'
2.2.0
$ rbenv local 2.3.0-dev
$ ruby -e 'puts RUBY_VERSION;$SAFE=1;require "stringio"'
2.3.0
```

**Comment by tamoot** [comment]
下記環境だと、$SAFE=1の場合 ``$LOAD_PATH`` 2個目のパスを探そうとしているところでSecurityErrorがでていました。

(別プラグインだと require 'socket' でSecurityErrorが出てしまい・・・)

* CentOS6.6
* Ruby2.2.2

```
ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-linux]
```

* rbenv
* zsh

## $LOAD_PATH

```
ruby -e '$SAFE=1; $LOAD_PATH.map{|lp| puts "#{lp} => #{lp.tainted?}"}'

/home/tamoot/.rbenv/rbenv.d/exec/gem-rehash => false
./lib => false
/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0 => false
/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/x86_64-linux => false
/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/site_ruby => false
/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/vendor_ruby/2.2.0 => false
/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/vendor_ruby/2.2.0/x86_64-linux => false
/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/vendor_ruby => false
/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/2.2.0 => false
/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/2.2.0/x86_64-linux => false

```

## $SAFE=0 の strace 抜粋

```
# 1個目
open("/home/tamoot/.rbenv/rbenv.d/exec/gem-rehash/stringio.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
# 2個目
open("/home/tamoot/workspace/github/tdiary-core/lib/stringio.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/stringio.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/x86_64-linux/stringio.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/site_ruby/stringio.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/vendor_ruby/2.2.0/stringio.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/vendor_ruby/2.2.0/x86_64-linux/stringio.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/vendor_ruby/stringio.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/2.2.0/stringio.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/2.2.0/x86_64-linux/stringio.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/tamoot/.rbenv/rbenv.d/exec/gem-rehash/stringio.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/tamoot/workspace/github/tdiary-core/lib/stringio.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/stringio.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/x86_64-linux/stringio.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/site_ruby/stringio.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/vendor_ruby/2.2.0/stringio.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/vendor_ruby/2.2.0/x86_64-linux/stringio.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/vendor_ruby/stringio.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/2.2.0/stringio.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/2.2.0/x86_64-linux/stringio.so", O_RDONLY|O_CLOEXEC) = 7
fstat(7, {st_mode=S_IFREG|0755, st_size=220829, ...}) = 0
close(7)                                = 0
open("/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/2.2.0/x86_64-linux/stringio.so", O_RDONLY) = 7
read(7, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\240\37\0\0\0\0\0\0"..., 832) = 832
fstat(7, {st_mode=S_IFREG|0755, st_size=220829, ...}) = 0
mmap(NULL, 2127280, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 7, 0) = 0x7f9c67e13000
mprotect(0x7f9c67e1a000, 2097152, PROT_NONE) = 0
mmap(0x7f9c6801a000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 7, 0x7000) = 0x7f9c6801a000
close(7)                                = 0
rt_sigaction(SIGINT, {SIG_IGN, [], SA_RESTORER, 0x7f9c6f321710}, {0x7f9c6f82d690, [], SA_RESTORER|SA_SIGINFO, 0x7f9c6f321710}, 8) = 0
rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7f9c6f321710}, {SIG_IGN, [], SA_RESTORER, 0x7f9c6f321710}, 8) = 0
write(1, "/home/tamoot/.rbenv/rbenv.d/exec"..., 639/home/tamoot/.rbenv/rbenv.d/exec/gem-rehash => false
./lib => false
/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0 => false
/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/x86_64-linux => false
/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/site_ruby => false
/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/vendor_ruby/2.2.0 => false
/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/vendor_ruby/2.2.0/x86_64-linux => false
/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/vendor_ruby => false
/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/2.2.0 => false
/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/2.2.0/x86_64-linux => false
2.2.2
) = 639
write(4, "!", 1)                        = 1
munmap(0x7f9c6f62f000, 1052672)         = 0
exit_group(0)                           = ?

```

## $SAFE=1 の strace抜粋

```
# 1個目
open("/home/tamoot/.rbenv/rbenv.d/exec/gem-rehash/stringio.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
# 2個目にいかない
write(2, "/home/tamoot/.rbenv/versions/2.2"..., 101/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require') = 101
write(2, ": ", 2: )                       = 2
write(2, "Insecure operation - gem_origina"..., 41Insecure operation - gem_original_require) = 41
write(2, " (", 2 ()                       = 2
write(2, "SecurityError", 13SecurityError)           = 13
write(2, ")\n", 2)
)                      = 2
write(2, "\tfrom /home/tamoot/.rbenv/versio"..., 108    from /home/tamoot/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
) = 108
write(2, "\tfrom -e:1:in `<main>'\n", 23        from -e:1:in `<main>'
) = 23
rt_sigaction(SIGINT, {SIG_IGN, [], SA_RESTORER, 0x7f51f33a9710}, {0x7f51f38b5690, [], SA_RESTORER|SA_SIGINFO, 0x7f51f33a9710}, 8) = 0
rt_sigaction(SIGINT, {SIG_DFL, [], SA_RESTORER, 0x7f51f33a9710}, {SIG_IGN, [], SA_RESTORER, 0x7f51f33a9710}, 8) = 0
write(4, "!", 1)                        = 1
munmap(0x7f51f36b7000, 1052672)         = 0
exit_group(1)                           = ?

```

**Comment by tamoot** [comment]
``$LOAD_PATH`` 中の相対パスとったら発生しなくなりました。

```
ruby -e 'puts RUBY_VERSION;$SAFE=1;$LOAD_PATH.delete("./lib");require "stringio"'
2.2.2
```

はて・・・・？(>_<)

**Comment by tamoot** [comment]
ワンライナーの現象については、手元では環境変数 ``RUBY_LIB`` が影響していました。まさに環境依存でした。

```
RUBYLIB="" ruby -e 'puts RUBY_VERSION;$SAFE=1;require "stringio"'
2.2.2
```

$SAFE > 0 かつ``$LOAD_PATH`` に相対パスが入っている場合、に発生しています。

```
RUBYLIB="" ruby -e 'puts RUBY_VERSION;$SAFE=1; $LOAD_PATH.unshift("./lib"); require "stringio"'
2.2.2
/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': Insecure operation - gem_original_require (SecurityError)
        from /home/tamoot/.rbenv/versions/2.2.2/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:1:in `<main>'
RUBYLIB="" ruby -e 'puts RUBY_VERSION;$SAFE=1; $LOAD_PATH.unshift("/home/tamoot/lib"); require "stringio"'
2.2.2
```


ということでtdiaryで "./lib" (とりあえず思いつき) を設定している個所がないか見てみました。
するとconfig.ruにありました。

```diff
diff --git a/config.ru b/config.ru
index ab8545f..7080f9b 100644
--- a/config.ru
+++ b/config.ru
@@ -1,4 +1,4 @@
-$:.unshift( File.join(File::dirname( __FILE__ ), 'lib' ).untaint )
+$:.unshift( File.join(File::expand_path(File::dirname( __FILE__ )), 'lib' ).untaint )
 require 'tdiary/application'

 use ::Rack::Reloader unless ENV['RACK_ENV'] == 'production'

```

上記の修正だと、 #483 の現象が発生しませんでした。本issueもこれで収まればいいのですが。


----

余談ですが、今度は Net::HTTPを利用するプラグインの延長で TCPSocket.open が InSecureOperation... 

```
SecurityError: Insecure operation - initialize
/home/tamoot/.rbenv/versions/2.2.2/lib/ruby/2.2.0/net/http.rb:879:in `initialize'
```

**Comment by tdtds** [comment]
地道な検証、ありがとうございます! 手元のunicorn環境で問題が出なくなることを確認しました。とりあえずこれを取り込んでクローズしますね。

**Comment by machu** [comment]
:thumbsup:
