### ISSUE TITLE
wikiスタイルだと日記が SecurityError: Insecure operation - eval で表示できない

### ISSUE THREAD

**Issue by tamoot** [tdiary/tdiary-core#553]
```
SecurityError: Insecure operation - eval
/home/tamoot/workspace/github_tdiary/tdiary-core/lib/tdiary/style/wiki.rb:78:in `eval'
/home/tamoot/workspace/github_tdiary/tdiary-core/lib/tdiary/style/wiki.rb:78:in `block in valid_plugin_syntax?'
/home/tamoot/workspace/github_tdiary/tdiary-core/lib/tdiary/style/wiki.rb:80:in `valid_plugin_syntax?'
/home/tamoot/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hikidoc-0.1.0/lib/hikidoc.rb:143:in `call'
/home/tamoot/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hikidoc-0.1.0/lib/hikidoc.rb:143:in `extract_plugin_block'
/home/tamoot/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hikidoc-0.1.0/lib/hikidoc.rb:104:in `escape_plugin_blocks'
/home/tamoot/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hikidoc-0.1.0/lib/hikidoc.rb:67:in `compile'
/home/tamoot/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hikidoc-0.1.0/lib/hikidoc.rb:50:in `to_html'
/home/tamoot/workspace/github_tdiary/tdiary-core/lib/tdiary/style/wiki.rb:87:in `to_html'
/home/tamoot/workspace/github_tdiary/tdiary-core/lib/tdiary/style/wiki.rb:35:in `initialize'
/home/tamoot/workspace/github_tdiary/tdiary-core/lib/tdiary/style/wiki.rb:200:in `new'
/home/tamoot/workspace/github_tdiary/tdiary-core/lib/tdiary/style/wiki.rb:200:in `append'
/home/tamoot/workspace/github_tdiary/tdiary-core/lib/tdiary/style.rb:112:in `replace'
```

* tdiary-core/lib/tdiary/style/wiki.rb
```ruby
			def valid_plugin_syntax?(code)
				lambda {
					begin
						$SAFE = 1
					ensure
						# ★ここで発生・・・★
						eval( "BEGIN {return true}\n#{code}", nil, "(plugin)", 0 )
					end
				}.call
			rescue SyntaxError
				lambda { eval('') }.call
				false
			end

```

* 環境

 * ruby 2.3.0p0 (2015-12-25 revision 53290) [i686-linux]
 * tDiary 2016/03/10のmasterを使用
 * tdiary.localに gem 'puma'を追記、 bundle installしてpumaで動作させています

* 暫定対処

 1. $SAFE=1をコメントアウトすると動きます(当たり前・・・

 2. untaintしてみました。動作しています。もっと前でuntaintしたほうがいいのかな？

```ruby
			def valid_plugin_syntax?(code)
				lambda {
					code.untaint!
					begin
						$SAFE = 1
					ensure
						# ★ここで発生・・・★
						eval( "BEGIN {return true}\n#{code}", nil, "(plugin)", 0 )
					end
				}.call
			rescue SyntaxError
				lambda { eval('') }.call
				false
			end

```

**Comment by tdtds** [comment]
手元のテスト環境では発生していないんですが、taintedな文字列がわたって来たらそうなるのは確かです。でも`untaint!`なんてメソッドなくないですか? `untaint`かな?

`code`を実行することなく`SyntaxError`を検知したいのだから、`code`を破壊的に`untaint`しない方が良さそう。`eval`の中で`dup.untaint`がいいかなぁ。これでどうですか?:

```ruby
eval( "BEGIN {return true}\n#{code.dup.untaint}", nil, "(plugin)", 0 )
```

**Comment by tamoot** [comment]
そうでした、untaintでした。

もうちょっと発生条件を追ってみました。

* 1. puma停止
* 2. cacheディレクトリを削除
* 3. とりあえずログをいれてみる

```ruby
			def valid_plugin_syntax?(code)
				lambda {
               $logger.info code
               $logger.info "tainted?=#{code.tainted?}"
					begin
						$SAFE = 1

```

* 4. puma起動
* 5. ログ確認

```
I, [2016-03-10T15:49:11.830929 #8577]  INFO -- : isbn '978-4-7741-7802-8'
I, [2016-03-10T15:49:11.830998 #8577]  INFO -- : tainted?=true
I, [2016-03-10T15:49:50.888181 #8577]  INFO -- : fn '昨年は・・・'
I, [2016-03-10T15:49:50.888254 #8577]  INFO -- : tainted?=true
I, [2016-03-10T15:51:02.754073 #8577]  INFO -- : fn '実は・・・'
I, [2016-03-10T15:53:55.492321 #8577]  INFO -- : flickr '25602915'
I, [2016-03-10T15:53:55.492645 #8577]  INFO -- : tainted?=true

```

私の日記では、footnoteプラグインとamazonプラグイン、flickrプラグインでした。

以下の修正でうまくうごきました！

```diff
diff --git a/lib/tdiary/style/wiki.rb b/lib/tdiary/style/wiki.rb
index 582edb8..056e802 100644
--- a/lib/tdiary/style/wiki.rb
+++ b/lib/tdiary/style/wiki.rb
@@ -75,7 +75,7 @@ module TDiary
                                        begin
                                                $SAFE = 1
                                        ensure
-                                               eval( "BEGIN {return true}\n#{code}", nil, "(plugin)", 0 )
+                                               eval( "BEGIN {return true}\n#{code.dup.untaint}", nil, "(plugin)", 0 )
                                        end
                                }.call
                        rescue SyntaxError

```

**Comment by tdtds** [comment]
あいかわらずこちらでは再現しないのですが(もしかすると他のプラグインの中で再帰的に呼ばれている場所かも知れません)、この修正自体は問題ないので、これでいきます。
