### ISSUE TITLE
日記を追加しようとすると category_legacy.rbで引数のエラーが発生する

### ISSUE THREAD

**Issue by tamoot** [tdiary/tdiary-core#554]
master追随環境です。とりあえずissueを。。。

```
wrong number of arguments (given 1, expected 0)

(plugin/category_legacy.rb):592:in `category_edit_support_dropdown'
(plugin/category.rb):209:in `block (3 levels) in load_plugin'
/home/tamoot/workspace/github_tdiary/tdiary-core/lib/tdiary/plugin.rb:116:in `block in transaction'
/home/tamoot/workspace/github_tdiary/tdiary-core/lib/tdiary/io/plugin_pstore.rb:38:in `block in plugin_transaction'
/home/tamoot/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pstore.rb:331:in `block in transaction'
/home/tamoot/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pstore.rb:330:in `catch'
/home/tamoot/.rbenv/versions/2.3.0/lib/ruby/2.3.0/pstore.rb:330:in `transaction'
/home/tamoot/workspace/github_tdiary/tdiary-core/lib/tdiary/compatible.rb:35:in `transaction'
/home/tamoot/workspace/github_tdiary/tdiary-core/lib/tdiary/io/plugin_pstore.rb:22:in `plugin_transaction'
/home/tamoot/workspace/github_tdiary/tdiary-core/lib/tdiary/plugin.rb:115:in `transaction'
(plugin/category.rb):205:in `block (2 levels) in load_plugin'
/home/tamoot/workspace/github_tdiary/tdiary-core/lib/tdiary/plugin.rb:245:in `block in edit_proc'
/home/tamoot/workspace/github_tdiary/tdiary-core/lib/tdiary/plugin.rb:244:in `each'
/home/tamoot/workspace/github_tdiary/tdiary-core/lib/tdiary/plugin.rb:244:in `edit_proc'
(TDiary::Plugin#eval_src):40:in `block in eval_src'
/home/tamoot/workspace/github_tdiary/tdiary-core/lib/tdiary/plugin.rb:107:in `eval'
/home/tamoot/workspace/github_tdiary/tdiary-core/lib/tdiary/plugin.rb:107:in `block in eval_src'
/home/tamoot/workspace/github_tdiary/tdiary-core/lib/tdiary/core_ext.rb:122:in `block in safe'
/home/tamoot/workspace/github_tdiary/tdiary-core/lib/tdiary/core_ext.rb:124:in `safe'
/home/tamoot/workspace/github_tdiary/tdiary-core/lib/tdiary/plugin.rb:106:in `eval_src'
```

有効にしているpluginでcategory関連は以下です。

* category.rb
* category_legacy.rb
* category_to_tag.rb
* category_to_tagcloud.rb

**Comment by tdtds** [comment]
category_legacyを使うときはcategoryを外して下さい。併用できません。あとでドキュメントを更新しておきます。

**Comment by tamoot** [comment]
わかりました。

caregory.rbを外すと、次は拙作category_autocomplete.rbでエラーになりました。まずはissueに。

```ruby
if /\A(?:form|preview|append|edit|update)\z/ =~ @mode
	add_header_proc do
		%Q|<link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.min.css"/>|
	end

	enable_js('//ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js')
	enable_js('caretposition.js')
	enable_js('category_autocomplete.js')

	if @categories.size > 0 # ここですね
```

**Comment by tdtds** [comment]
ああ、そうか。読み込みの順序が変わってしまったから、category_legacy.rbより先にcategory_autocomplete.rbが読まれてしまうんですね……うーん、どうしようかな。

本音を言うと、category_autocompleteはcategory_legacyと併用してほしくないんですけどね。

**Comment by hsbt** [comment]
category_autocomplete.rb に plugin の enabled をもとに eval するコードを入れる、とかですかねえ...

**Comment by tdtds** [comment]
category_legacy.rbをcategory-legacy.rb (アンダースコアをハイフンに)変えれば読み込み順問題は解消するのはわかっているんだけど、あえてそうしなかった記憶があって、でも理由が思い出せない……

**Comment by tdtds** [comment]
……思い出せないので 976ad5e9b795b059660015d6cabf727def00bfa5 で名前を変えました。
