### ISSUE TITLE
5.0.1でbundle install時に--without developmentをつけているとrakeタスクを実行できない

### ISSUE THREAD

**Issue by minimum2scp** [tdiary/tdiary-core#575]
tDiary 5.0.1 の Docker イメージを作ろうとして気付いたのですが、
tdiary-core を git clone していて、かつ bundle install で --without development をつけている環境だと
rake タスクが使えなくなっていました。（ https://github.com/tdiary/tdiary-core/pull/573 の影響だと思います）

```
% git clone https://github.com/tdiary/tdiary-core.git -b v5.0.1
Cloning into 'tdiary-core'...
(snip)
% cd tdiary-core
% bundle install --without development
(snip)
% bundle exec rake -vT
rake aborted!
LoadError: cannot load such file -- octokit
/home/debian/tdiary-core/lib/tdiary/tasks/release.rake:4:in `require'
/home/debian/tdiary-core/lib/tdiary/tasks/release.rake:4:in `<top (required)>'
/home/debian/tdiary-core/lib/tdiary/tasks.rb:1:in `load'
/home/debian/tdiary-core/lib/tdiary/tasks.rb:1:in `block in <top (required)>'
/home/debian/tdiary-core/lib/tdiary/tasks.rb:1:in `each'
/home/debian/tdiary-core/lib/tdiary/tasks.rb:1:in `<top (required)>'
/home/debian/tdiary-core/Rakefile:4:in `require'
/home/debian/tdiary-core/Rakefile:4:in `<top (required)>'
/var/lib/gems/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
(See full trace by running task with --trace)
```

v5.0.0 までは rake タスクをたたくことができていました。

```
% git checkout v5.0.0
(snip)
% bundle install --without development
(snip)
% bundle exec rake -vT
rake assets:copy              # copy assets files
rake auth:password:create     # create password
rake build                    # Build tdiary-5.0.0.gem into the pkg directory
rake clean                    # Remove any temporary products
rake clobber                  # Remove any generated files
rake doc                      # generate document files
rake install                  # Build and install tdiary-5.0.0.gem into system gems
rake install:local            # Build and install tdiary-5.0.0.gem into system gems without network access
rake jasmine                  # Start server to host jasmine specs
rake jasmine:ci[random,seed]  # Run jasmine tests in a browser, random and seed override config
rake mongodb:index            # make index into mongoDB
rake package:clean            # cleanup all files
rake package:fetch            # fetching all files from GitHub
rake package:release          # releasing all files
rake package:snapshot         # making packages of snapshot
rake package:stable           # making packages of stable
rake rdoc                     # generate rdoc files
rake release[remote]          # Create tag v5.0.0 and build and push tdiary-5.0.0.gem to Rubygems
```

ひとまず手元では Gemfile.local に

```
gem "octokit"
```

を書く、というワークアラウンドで回避しています。

**Comment by tdtds** [comment]
なるほど。 #577 な感じでどうですかねぇ /cc @machu

**Comment by minimum2scp** [comment]
別解で #578 を作りました。
#577 は release.rake にあるタスク全部無効にしちゃいますが、
#578 は `rake package:release` 実行時にエラーにするというものです。
どちらが良いかはお任せします。（実際にリリースする人が良い方で…）

**Comment by machu** [comment]
release.rakeを使うのはdeveloperだけなので、一括で無効にしちゃって良さそうです。修正はどちらも良さげです。今後、他のライブラリに依存した場合にも影響ないのは #577 ですね。

**Comment by tdtds** [comment]
では #577 をマージします。 @minimum2scp さん、ありがとう。
