### ISSUE TITLE
CGI環境でtDiaryが起動できない

### ISSUE THREAD

**Issue by machu** [tdiary/tdiary-core#662]
CGI環境でパッケージ版のtDiaryを起動しようとすると、bundlerのエラーが発生する。

### tDiaryの取得元

https://github.com/tdiary/tdiary-core/releases/download/v5.0.7/tdiary-v5.0.7.tar.gz

### 環境

 * Debian jessie
 * ruby 2.1.5p273
 * apache-httpd 2.4.29

### エラーメッセージ

```
500 Internal Server Error

Could not find rake-12.3.0 in any of the sources (Bundler::GemNotFound)

/usr/local/apache2/htdocs/tdiary/misc/lib/bundler-1.16.1/lib/bundler/spec_set.rb:88:in `block in materialize'
/usr/local/apache2/htdocs/tdiary/misc/lib/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `map!'
/usr/local/apache2/htdocs/tdiary/misc/lib/bundler-1.16.1/lib/bundler/spec_set.rb:82:in `materialize'
/usr/local/apache2/htdocs/tdiary/misc/lib/bundler-1.16.1/lib/bundler/definition.rb:170:in `specs'
/usr/local/apache2/htdocs/tdiary/misc/lib/bundler-1.16.1/lib/bundler/definition.rb:237:in `specs_for'
/usr/local/apache2/htdocs/tdiary/misc/lib/bundler-1.16.1/lib/bundler/definition.rb:226:in `requested_specs'
/usr/local/apache2/htdocs/tdiary/misc/lib/bundler-1.16.1/lib/bundler/runtime.rb:108:in `block in definition_method'
/usr/local/apache2/htdocs/tdiary/misc/lib/bundler-1.16.1/lib/bundler/runtime.rb:20:in `setup'
/usr/local/apache2/htdocs/tdiary/misc/lib/bundler-1.16.1/lib/bundler.rb:107:in `setup'
/usr/local/apache2/htdocs/tdiary/misc/lib/bundler-1.16.1/lib/bundler/setup.rb:20:in `<top (required)>'
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/apache2/htdocs/tdiary/lib/tdiary/environment.rb:8:in `<top (required)>'
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/apache2/htdocs/tdiary/lib/tdiary.rb:25:in `<top (required)>'
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/apache2/htdocs/tdiary/index.cgi:18:in `<main>'
```

**Comment by tdtds** [comment]
これはruby 2.1で動かそうとしているから?

サポート掲示板の方で2.5向けのgemがバンドルされていないという指摘があって再パッケージしたけど、それによって動作するようになったという報告は受けています。

see http://tdiary-users.osdn.jp/cgi-bin/wforum/wforum.cgi?mode=allread&no=6815&page=0

**Comment by machu** [comment]
そうですね。tdiary-5.0.7はruby 2.1系では動かせなかったでしたね。
その後の調べで、tdiary-5.0.6もruby2.1系で動かないことが分かりました。パッケージ内でruby2.1.0フォルダが空になっているので、パッケージングミスのようです。Twitterでの動かない報告はこちらかも。

**Comment by tdtds** [comment]
あれ、ruby 2.1のサポートを切ったのは2017-01-20 (tDiary 5.0.4リリース前)なので、tDiary 5.0.4以降のパッケージに2.1.0のフォルダがあるとしたらおかしい。

**Comment by tdtds** [comment]
すでに問題ではなくなっているのでcloseします。
