### ISSUE TITLE
twitter.rb プラグインを利用すると REXML::ParseException が発生する

### ISSUE THREAD

**Issue by bynnchapu** [tdiary/tdiary-core#889]
**Describe the bug / 不具合の説明**
twitter.rb を有効な状態にしたところ、 `REXML::ParseException` が発生します。

**To Reproduce / 再現手順**
update.rb?conf=sp にて、 `twitter.rb` を有効にします。

**Expected behavior / 期待した動作**
自身の tDiary サイトが表示される。

**Screenshots / スクリーンショット**
![image](https://user-images.githubusercontent.com/1008151/83959403-772ada00-a8b7-11ea-93bc-2cb1c2575bb4.png)

スタックトレースは以下のとおりです。
```
REXML::ParseException
Missing attribute equal: <data-rdm>
Line: 72
Position: 7136
Last 80 unconsumed characters:
/usr/local/lib/ruby/2.7.0/rexml/parsers/baseparser.rb:519:in `block in parse_attributes'
/usr/local/lib/ruby/2.7.0/rexml/parsers/baseparser.rb:510:in `loop'
/usr/local/lib/ruby/2.7.0/rexml/parsers/baseparser.rb:510:in `parse_attributes'
/usr/local/lib/ruby/2.7.0/rexml/parsers/baseparser.rb:378:in `pull_event'
/usr/local/lib/ruby/2.7.0/rexml/parsers/baseparser.rb:183:in `pull'
/usr/local/lib/ruby/2.7.0/rexml/parsers/treeparser.rb:23:in `parse'
/usr/local/lib/ruby/2.7.0/rexml/document.rb:288:in `build'
/usr/local/lib/ruby/2.7.0/rexml/document.rb:45:in `initialize'
(plugin/twitter.rb):21:in `new'
(plugin/twitter.rb):21:in `block (2 levels) in load_plugin'
/usr/src/app/lib/tdiary/plugin.rb:114:in `block in header_proc'
/usr/src/app/lib/tdiary/plugin.rb:113:in `each'
/usr/src/app/lib/tdiary/plugin.rb:113:in `header_proc'
(TDiary::Plugin#eval_src):5:in `eval_src'
/usr/src/app/lib/tdiary/plugin.rb:95:in `eval'
/usr/src/app/lib/tdiary/plugin.rb:95:in `eval_src'
/usr/src/app/lib/tdiary/base.rb:65:in `do_eval_rhtml'
/usr/src/app/lib/tdiary/base.rb:29:in `eval_rhtml'
/usr/src/app/lib/tdiary/dispatcher/index_main.rb:37:in `run'
/usr/src/app/lib/tdiary/dispatcher/index_main.rb:5:in `run'
/usr/src/app/lib/tdiary/dispatcher.rb:25:in `dispatch_cgi'
/usr/src/app/lib/tdiary/dispatcher.rb:20:in `call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/urlmap.rb:74:in `block in call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/urlmap.rb:58:in `each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/urlmap.rb:58:in `call'
/usr/src/app/lib/tdiary/rack/valid_request_path.rb:15:in `block in call'
/usr/src/app/lib/tdiary/rack/valid_request_path.rb:14:in `each'
/usr/src/app/lib/tdiary/rack/valid_request_path.rb:14:in `call'
/usr/src/app/lib/tdiary/rack/static.rb:20:in `call'
/usr/src/app/lib/tdiary/rack/html_anchor.rb:19:in `call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/urlmap.rb:74:in `block in call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/urlmap.rb:58:in `each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/urlmap.rb:58:in `call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/urlmap.rb:74:in `block in call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/urlmap.rb:58:in `each'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/urlmap.rb:58:in `call'
/usr/src/app/lib/tdiary/application.rb:52:in `call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/reloader.rb:49:in `call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/tempfile_reaper.rb:15:in `call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/lint.rb:50:in `_call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/lint.rb:38:in `call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/show_exceptions.rb:23:in `call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/common_logger.rb:38:in `call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/rack-2.2.2/lib/rack/content_length.rb:17:in `call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/puma-4.3.5/lib/puma/configuration.rb:228:in `call'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/puma-4.3.5/lib/puma/server.rb:713:in `handle_request'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/puma-4.3.5/lib/puma/server.rb:472:in `process_client'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/puma-4.3.5/lib/puma/server.rb:328:in `block in run'
/usr/src/app/vendor/bundle/ruby/2.7.0/gems/puma-4.3.5/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Environment / 動作環境**
Docker イメージ版の tdiary を利用しています。
 - ホストOS: CentOS7.8.2003
    - Docker version: Docker version 1.13.1, build 64e9980/1.13.1
        - CentOS rpm version: docker-1.13.1-161.git64e9980.el7_8.x86_64
 - Browser: Google Chrome 83.0.4103.61 for Windows
- tDiary Docker image: tdiary/tdiary:latest `2a1f11a2cc62bfd4e903fc63d0cc9d6f80de199224cc05e091af8c2c89dee0e7`
    - 切り分けのために、最新のイメージを利用してみましたが、同様でした。
 - tDiary Version:  tDiary version 5.1.2
    - Ruby Version: Powered by Ruby version 2.7.1-p83

**Comment by tdtds** [comment]
報告ありがとうございます！ 反応が遅くてすみません。
twitterプラグインはcontribパッケージなので、あちらに移って対応しますね。 https://github.com/tdiary/tdiary-contrib/issues/220
